build.gradle.kts

1) Update spring security
2) Remove netty
3) Update webflux
4) Update kotlin version

EIP1-6010 Spring Security

---

src/main/resources/messages.properties
src/main/resources/messages_cy.properties
src/main/resources/messages_en.properties
src/main/resources/openapi/NotificationsAPIs.yaml
src/main/resources/openapi/sqs/Notifications-sqs-messaging.yaml
src/test/kotlin/uk/gov/dluhc/notificationsapi/mapper/RejectedSignatureReasonMapperTest.kt
src/test/kotlin/uk/gov/dluhc/notificationsapi/mapper/RejectedSignatureTemplatePreviewDtoMapperTest.kt
src/test/kotlin/uk/gov/dluhc/notificationsapi/messaging/mapper/TemplatePersonalisationMessageMapperTest.kt
src/test/kotlin/uk/gov/dluhc/notificationsapi/rest/GenerateRejectedSignatureTemplatePreviewIntegrationTest.kt
src/test/kotlin/uk/gov/dluhc/notificationsapi/testsupport/testdata/api/GenerateRejectedSignatureTemplatePreviewRequestBuilder.kt
src/test/kotlin/uk/gov/dluhc/notificationsapi/testsupport/testdata/messaging/models/SendNotifyRejectedSignatureMessageBuilder.kt

https://technologyprogramme.atlassian.net/browse/EIP1-7167
- Changed signature rejection reasons in specs, mappers
- Translated signature rejection reasons into Welsh
- Updated tests

EIP1-7167: Signature rejection reason changes

---

src/main/kotlin/uk/gov/dluhc/notificationsapi/rest/StatisticsController.kt
src/main/kotlin/uk/gov/dluhc/notificationsapi/service/SendNotificationService.kt
src/test/kotlin/uk/gov/dluhc/notificationsapi/service/SendNotificationServiceTest.kt

Notification types weren't as expected for Postal - updated in this PR to ensure stats are updated correctly when notifications are sent

EIP1-8103 Updating notification statistics notification types

---

src/main/resources/openapi/sqs/proxy-api-sqs-messaging-erop.yaml

Capitalisation issue breaking queue

Eip1 8742 proxy queue message fix

---

src/main/kotlin/uk/gov/dluhc/notificationsapi/rest/SentCommunicationsController.kt

https://dluhcdigital.atlassian.net/browse/EIP1-9649

EIP1-9649: Remove trailing slash in request mapping

---

src/main/kotlin/uk/gov/dluhc/notificationsapi/rest/GlobalExceptionHandler.kt

https://dluhcdigital.atlassian.net/browse/EIP1-9649

EIP1-9649: Return error message when a required query parameter is missing

---

src/main/kotlin/uk/gov/dluhc/notificationsapi/dto/BespokeCommTemplatePreviewDto.kt
src/main/kotlin/uk/gov/dluhc/notificationsapi/mapper/BespokeCommTemplatePreviewDtoMapper.kt
src/main/kotlin/uk/gov/dluhc/notificationsapi/mapper/SourceTypeMapper.kt
src/main/kotlin/uk/gov/dluhc/notificationsapi/rest/TemplateController.kt
src/main/kotlin/uk/gov/dluhc/notificationsapi/service/TemplateService.kt
src/main/resources/openapi/NotificationsAPIs.yaml
src/test/kotlin/uk/gov/dluhc/notificationsapi/mapper/BespokeCommTemplatePreviewDtoMapperTest.kt
src/test/kotlin/uk/gov/dluhc/notificationsapi/rest/GenerateBespokeCommTemplatePreviewIntegrationTest.kt
src/test/kotlin/uk/gov/dluhc/notificationsapi/service/TemplateServiceTest.kt
src/test/kotlin/uk/gov/dluhc/notificationsapi/testsupport/annotations/CommunicationChannelsTest.kt
src/test/kotlin/uk/gov/dluhc/notificationsapi/testsupport/annotations/SourceTypesApiEnumTest.kt
src/test/kotlin/uk/gov/dluhc/notificationsapi/testsupport/testdata/api/GenerateBespokeCommTemplatePreviewRequestBuilder.kt
src/test/kotlin/uk/gov/dluhc/notificationsapi/testsupport/testdata/dto/BespokeCommTemplatePreviewDtoBuilder.kt
src/test/resources/application-integration-test.yml

Notifications API work for previewing a bespoke comm
https://dluhcdigital.atlassian.net/browse/EIP1-9922

EIP1-9922-bespoke-comm-preview

---

src/main/kotlin/uk/gov/dluhc/notificationsapi/dto/TemplatePersonalisationDto.kt
src/main/kotlin/uk/gov/dluhc/notificationsapi/mapper/InviteToRegisterTemplatePreviewDtoMapper.kt
src/main/kotlin/uk/gov/dluhc/notificationsapi/mapper/TemplatePersonalisationDtoMapper.kt
src/main/kotlin/uk/gov/dluhc/notificationsapi/messaging/mapper/TemplatePersonalisationMessageMapper.kt
src/main/resources/openapi/NotificationsAPIs.yaml
src/main/resources/openapi/sqs/Notifications-sqs-messaging.yaml
src/test/kotlin/uk/gov/dluhc/notificationsapi/mapper/InviteToRegisterTemplatePreviewDtoMapperTest.kt
src/test/kotlin/uk/gov/dluhc/notificationsapi/messaging/mapper/TemplatePersonalisationMessageMapperTest.kt
src/test/kotlin/uk/gov/dluhc/notificationsapi/rest/GenerateInviteToRegisterTemplatePreviewIntegrationTest.kt
src/test/kotlin/uk/gov/dluhc/notificationsapi/testsupport/testdata/api/GenerateInviteToRegisterTemplatePreviewRequestBuilder.kt
src/test/kotlin/uk/gov/dluhc/notificationsapi/testsupport/testdata/dto/TemplatePersonalisationDtoBuilder.kt
src/test/kotlin/uk/gov/dluhc/notificationsapi/testsupport/testdata/messaging/models/SendNotifyInviteToRegisterMessageBuilder.kt

I thought address was already mapped through for personalisation as it's included in the letter.
It however does not quite work like that if it is needed in the body and needs its own mapping 
https://dluhcdigital.atlassian.net/browse/EIP1-10347
https://dluhcdigital.atlassian.net/browse/EIP1-10357

EIP1-10357-10347-address-mapping map address for personalisation

---

src/main/kotlin/uk/gov/dluhc/notificationsapi/rest/StatisticsController.kt
src/main/kotlin/uk/gov/dluhc/notificationsapi/service/SendNotificationService.kt
src/main/resources/openapi/NotificationsAPIs.yaml
src/test/kotlin/uk/gov/dluhc/notificationsapi/messaging/SendNotifyInviteToRegisterMessageListenerIntegrationTest.kt
src/test/kotlin/uk/gov/dluhc/notificationsapi/rest/GetCommunicationStatisticsByApplicationIdIntegrationTest.kt
src/test/kotlin/uk/gov/dluhc/notificationsapi/service/SendNotificationServiceTest.kt

Include has sent invite to register in statistics message
https://dluhcdigital.atlassian.net/browse/EIP1-10513

EIP1-10513 add hasSentNotRegisteredToVoteCommunication to statistics message

---

src/main/resources/openapi/NotificationsAPIs.yaml

Correct api gateway integration url for moved get communication endpoint
https://dluhcdigital.atlassian.net/browse/EIP1-10517

EIP1-10517: Move get communication endpoint - fix api gateway integration

---

src/main/resources/openapi/NotificationsAPIs.yaml

Adds `requestParameter` for `applicationId` to the api gateway for the get communication endpoint
https://dluhcdigital.atlassian.net/browse/EIP1-10517

EIP1-10517: Add application id parameter to api gateway - add requestParameter

---

src/main/kotlin/uk/gov/dluhc/notificationsapi/rest/StatisticsController.kt
src/main/resources/openapi/NotificationsAPIs.yaml
src/test/kotlin/uk/gov/dluhc/notificationsapi/rest/GetCommunicationStatisticsByApplicationIdIntegrationTest.kt

Provide statistic for number of signature/identity requests made
https://dluhcdigital.atlassian.net/browse/EIP1-10370

EIP1-10370-communication-count-stat

---

build.gradle.kts
src/main/kotlin/uk/gov/dluhc/notificationsapi/config/MessagingConfiguration.kt
src/main/kotlin/uk/gov/dluhc/notificationsapi/service/SendNotificationService.kt
src/main/kotlin/uk/gov/dluhc/notificationsapi/service/StatisticsUpdateService.kt
src/main/resources/application.yml
src/main/resources/openapi/sqs/overseas-api-sqs-messaging-erop.yaml
src/test/kotlin/uk/gov/dluhc/notificationsapi/config/IntegrationTest.kt
src/test/kotlin/uk/gov/dluhc/notificationsapi/config/LocalStackContainerConfiguration.kt
src/test/kotlin/uk/gov/dluhc/notificationsapi/messaging/SendNotifyBespokeCommMessageListenerIntegrationTest.kt
src/test/kotlin/uk/gov/dluhc/notificationsapi/messaging/SendNotifyNotRegisteredToVoteMessageListenerIntegrationTest.kt
src/test/kotlin/uk/gov/dluhc/notificationsapi/service/SendNotificationServiceTest.kt
src/test/kotlin/uk/gov/dluhc/notificationsapi/service/StatisticsUpdateServiceTest.kt
src/test/kotlin/uk/gov/dluhc/notificationsapi/stubs/UpdateOverseasStatisticsMessageListenerStub.kt
src/test/resources/application-integration-test.yml

https://dluhcdigital.atlassian.net/browse/EIP1-10370

EIP1-10370-send-stat-update-after-oe-comm

---

src/main/kotlin/uk/gov/dluhc/notificationsapi/dto/TemplatePersonalisationDto.kt
src/main/kotlin/uk/gov/dluhc/notificationsapi/mapper/NotRegisteredToVoteTemplatePreviewDtoMapper.kt
src/main/kotlin/uk/gov/dluhc/notificationsapi/mapper/TemplatePersonalisationDtoMapper.kt
src/main/kotlin/uk/gov/dluhc/notificationsapi/messaging/mapper/TemplatePersonalisationMessageMapper.kt
src/main/resources/openapi/NotificationsAPIs.yaml
src/main/resources/openapi/sqs/Notifications-sqs-messaging.yaml
src/test/kotlin/uk/gov/dluhc/notificationsapi/mapper/NotRegisteredToVoteTemplatePreviewDtoMapperTest.kt
src/test/kotlin/uk/gov/dluhc/notificationsapi/messaging/SendNotifyNotRegisteredToVoteMessageListenerIntegrationTest.kt
src/test/kotlin/uk/gov/dluhc/notificationsapi/messaging/mapper/TemplatePersonalisationMessageMapperTest.kt
src/test/kotlin/uk/gov/dluhc/notificationsapi/rest/GenerateNotRegisteredToVoteTemplatePreviewIntegrationTest.kt
src/test/kotlin/uk/gov/dluhc/notificationsapi/testsupport/testdata/api/GenerateNotRegisteredToVoteTemplatePreviewRequestBuilder.kt
src/test/kotlin/uk/gov/dluhc/notificationsapi/testsupport/testdata/dto/TemplatePersonalisationDtoBuilder.kt
src/test/kotlin/uk/gov/dluhc/notificationsapi/testsupport/testdata/messaging/models/SendNotifyNotRegisteredToVoteMessageBuilder.kt

Add deadline to personalisation
https://dluhcdigital.atlassian.net/browse/EIP1-11020

EIP1-11020-not-registererd-to-vote-add-deadline 

---

.github/workflows/deploy-from-version-tag.yml

https://dluhcdigital.atlassian.net/browse/EROPSPT-406

EROPSPT-406: Remove sb and dev environments from workflows

---

.github/workflows/build-and-test.yml
.github/workflows/owasp-dependency-check.yml
build.gradle.kts
owasp.suppressions.xml

https://dluhcdigital.atlassian.net/browse/EIP1-

EROPSPT-419: Feb/Mar 2025 vulnerability patching

---

src/main/kotlin/uk/gov/dluhc/notificationsapi/rest/StatisticsController.kt
src/test/kotlin/uk/gov/dluhc/notificationsapi/rest/GetCommunicationStatisticsByApplicationIdIntegrationTest.kt

Fix communication statistics retrieval (again!) since `VOTER_CARD` was being sent as `voter-card` and the service was expecting `vac`.
https://dluhcdigital.atlassian.net/browse/EIP1-11740

EIP1-11740: Fix application source value

---

build.gradle.kts
owasp.suppressions.xml
src/test/kotlin/uk/gov/dluhc/notificationsapi/client/ElectoralRegistrationOfficeManagementApiClientTest.kt
src/test/kotlin/uk/gov/dluhc/notificationsapi/client/GovNotifyApiClientTest.kt
src/test/kotlin/uk/gov/dluhc/notificationsapi/database/repository/NotificationRepositoryIntegrationTest.kt
src/test/kotlin/uk/gov/dluhc/notificationsapi/mapper/NotificationTypeMapperTest.kt
src/test/kotlin/uk/gov/dluhc/notificationsapi/service/EroServiceTest.kt
src/test/kotlin/uk/gov/dluhc/notificationsapi/service/RemoveNotificationsServiceTest.kt

https://dluhcdigital.atlassian.net/browse/EIP1-

EROPSPT-443: Upgrade to SB 3.4, dependency checker to 12, and remove some suppressions

---

build.gradle.kts
src/main/kotlin/uk/gov/dluhc/notificationsapi/config/SecurityConfiguration.kt
src/main/kotlin/uk/gov/dluhc/notificationsapi/dto/LanguageDto.kt
src/test/kotlin/uk/gov/dluhc/notificationsapi/testsupport/RandomUtils.kt
src/test/kotlin/uk/gov/dluhc/notificationsapi/testsupport/testdata/CommonDataBuilder.kt

https://dluhcdigital.atlassian.net/browse/EIP1-

EROPSPT-503: Upgrade to Spring Boot 3.5

---

.github/pull_request_template.md

Small update to PR template to only have relevant checks

EIP1-NONE: Update PR template

---

.github/workflows/owasp-dependency-check.yml
build.gradle.kts

https://dluhcdigital.atlassian.net/browse/EIP1-
- Can leave tags as tbd until merged

EROPSPT-480: Bump dependency check and pass OSS Index credentials
